### ISSUE TITLE
Bug? Books don't unlock the stages

### ISSUE THREAD

**Issue by CobaltRealm** [xt9/gamestagebooks#1]
I've created the books with the script and it works just fine, but in-game the books do nothing

**Comment by xt9** [comment]
I need to see the scriptfile and a logfile where you tried to consume a book. 
Are you on GameStages 2.0 or later? They changed the API for giving the player stages when moving from v1 to v2. (So only v2+ is supported)

**Comment by CobaltRealm** [comment]
I'm in GameStages 1.0.86, I'll try with version 2.0

scriptfile:
https://pastebin.com/v6PaRM0g

logfile?:
https://pastebin.com/PZKcVLw1

**Comment by xt9** [comment]
Yeah the errors in the log should go away if you upgrade to 2.0+

**Comment by CobaltRealm** [comment]
I think the problem should be fixed, but when I start the game it crashes, I've submited the issue in the GameStages github

https://github.com/Darkhax-Minecraft/Game-Stages/issues/24

**Comment by xt9** [comment]
Well 2.0.91 should work. But I see you're using old versions of other mods that depend on Gamestages 1.0, For example your orestages version is **1.0.23**, Support for gamestages 2.0 wasn't added until orestages **2.0.27**

**Comment by CobaltRealm** [comment]
Okay so I'll try updating all the GameStages mods
