### ISSUE TITLE
Still crash time to time

### ISSUE THREAD

**Issue by DevTimur** [xt9/gamestagebooks#3]
https://pastebin.com/2msPLfTJ
gamestagebooks-1.12.2-1.0.0-universal.jar

https://pastebin.com/yn44ZgrZ Example of script

Description: Not every time i crash, but mostly when just loaded game and it's still a little laggy.

**Comment by xt9** [comment]
One of your items must be an invalid itemstack.
When I get the time I'll double back and add some extra errorchecking to the mod so it's more apparent where the error in your script is.

**Comment by xt9** [comment]
Might be fixed in 1c1799ca3e87f341c07fb0018424d1a2599e3198. Reopen this issue if the crash happens on 1.0.1
